"""empty message

Revision ID: 80cd9bfd0a8b
Revises: b0405a96398f
Create Date: 2021-03-06 18:09:11.000663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80cd9bfd0a8b'
down_revision = 'b0405a96398f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('nearby_locations', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['map_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maps')
    # ### end Alembic commands ###
